// Generated by CoffeeScript 2.4.1
(function() {
  var init;

  init = function() {
    var client, i, j, len, ref, ws_obj;
    ws_obj = new WS_Object('wss://' + location.host + '/apps/ws-obj-example');
    ref = [0, 1];
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      client = new WS_Client_View('views', i, ws_obj);
      ws_obj.views.push(client);
    }
    return window.app = {
      ws_obj: ws_obj
    };
  };

  init();

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoid3NfZXhhbXBsZS5qcyIsInNvdXJjZVJvb3QiOiIuLi8uLiIsInNvdXJjZXMiOlsic3JjL2NvZmZlZS93c19leGFtcGxlLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBRUE7QUFBQSxNQUFBOztFQUFBLElBQUEsR0FBTyxRQUFBLENBQUEsQ0FBQTtBQUNMLFFBQUEsTUFBQSxFQUFBLENBQUEsRUFBQSxDQUFBLEVBQUEsR0FBQSxFQUFBLEdBQUEsRUFBQTtJQUFBLE1BQUEsR0FBUyxJQUFJLFNBQUosQ0FBYyxRQUFBLEdBQVcsUUFBUSxDQUFDLElBQXBCLEdBQTJCLHNCQUF6QztBQUNUO0lBQUEsS0FBQSxxQ0FBQTs7TUFDRSxNQUFBLEdBQVMsSUFBSSxjQUFKLENBQW1CLE9BQW5CLEVBQTRCLENBQTVCLEVBQStCLE1BQS9CO01BQ1QsTUFBTSxDQUFDLEtBQUssQ0FBQyxJQUFiLENBQWtCLE1BQWxCO0lBRkY7V0FJQSxNQUFNLENBQUMsR0FBUCxHQUNFO01BQUEsTUFBQSxFQUFRO0lBQVI7RUFQRzs7RUFTUCxJQUFBLENBQUE7QUFUQSIsInNvdXJjZXNDb250ZW50IjpbIlxuXG5pbml0ID0gLT5cbiAgd3Nfb2JqID0gbmV3IFdTX09iamVjdCgnd3NzOi8vJyArIGxvY2F0aW9uLmhvc3QgKyAnL2FwcHMvd3Mtb2JqLWV4YW1wbGUnKVxuICBmb3IgaSBpbiBbMCwxXVxuICAgIGNsaWVudCA9IG5ldyBXU19DbGllbnRfVmlldygndmlld3MnLCBpLCB3c19vYmopXG4gICAgd3Nfb2JqLnZpZXdzLnB1c2goY2xpZW50KVxuXG4gIHdpbmRvdy5hcHAgPSBcbiAgICB3c19vYmo6IHdzX29ialxuXG5pbml0KClcblxuXG4gICAgXG4iXX0=
//# sourceURL=/var/www/git/projects/ws_obj/src/coffee/ws_example.coffee